### PR TITLE
fix issue #11 by using lsregister

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by phlummox** [comment]
... @fenollp, I think this patch may cause runtime errors when used - have you tried using it on a repo yourself?

It seems to include a backtick ([here, in a comment][bad-backtick]) inside a backtick-string (starting [here][backtick-start]), meaning the backstick string is interpreted as ending early.

[bad-backtick]: https://github.com/docker-practice/actions-setup-docker/blob/4c5b33b7186fe8d6d92ed0db3412d29dc10421c0/lib/setup-docker.js#L207

[backtick-start]: https://github.com/docker-practice/actions-setup-docker/blob/4c5b33b7186fe8d6d92ed0db3412d29dc10421c0/lib/setup-docker.js#L163

**Comment by phlummox** [comment]
p.s. I have a "fix to the fix" here: https://github.com/phlummox-dev/actions-setup-docker/commit/aeefd9ac1777ed7acbc8a2b88a8dbf7bd1de0b06

**Comment by fenollp** [comment]
Thanks for the review and the fix! I've merged it.
Here's a successful CI run of this branch as proof of it working: https://github.com/fenollp/actions-setup-docker/actions/runs/1658390147

**Comment by phlummox** [comment]
No worries, glad it was useful :)

**Pull request closed without merging**
